### ISSUE TITLE
Pre Flight check fails with no clear reason and log of the failure/details

### ISSUE THREAD

**Issue by sanusatyadarshi** [aws-samples/amazon-eks-one-click-cluster-upgrade#2]
`ubuntu@ip-xxxxx:~/amazon-eks-one-click-cluster-upgrade$ python3 eks_updater.py myCluster 1.22 ap-southeast-1 --preflight
/home/ubuntu/.local/lib/python3.6/site-packages/boto3/compat.py:88: PythonDeprecationWarning: Boto3 will no longer support Python 3.6 starting May 30, 2022. To continue receiving service updates, bug fixes, and security updates please upgrade to Python 3.7 or later. More information can be found here: https://aws.amazon.com/blogs/developer/python-support-policy-updates-for-aws-sdks-and-tools/
  warnings.warn(warning, PythonDeprecationWarning)
Check logs in cloud watch group cluster-myCluster-ap-southeast-1 for more informationin stream preflight-checks-16xxxxx

Verifying User IAM Role....
IAM role for user verified

Fetching cluster details .....
Cluster control plane version 1.21
Cluster with verison 1.21 cannot be updated to target version 1.22

Preflight unsuccessful because of following errors
Cluster with verison 1.21 cannot be updated to target version 1.22

Pre flight check for cluster myCluster failed`

**Comment by sanusatyadarshi** [comment]
https://github.com/aws-samples/amazon-eks-one-click-cluster-upgrade/blob/b9fcddfe0acb45a0d400177141603962a9ba322e/eksupdate/src/preflight_module.py#L127

This seems due to the condition **(update_version) < 1.22**

**Comment by onabison** [comment]
Was there any update on this? I am facing the same issue. I don't think there was any resolution. this case is still open.
